Algoritmo "semnome"
//Disciplina : Internet e Programação web
//Professor  : reisalucasg
//Descrição   : algoritimos de teste
// Autor(a)    : Lucas Gabriel Volk Dos Santos
// Data atual  : 22/09/2022
Var
// Seção de Declarações das variáveis 
   x, y, z:inteiro
Inicio

// Seção de Comandos, procedimento, funções, operadores, etc... 
   x<- 10;
   y<- 5;
   z<- x + y;
   escreva("essa soma é ", z)

Fimalgoritmo