Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2022
Var
// Seção de Declarações das variáveis 
   peso,altura,imc:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira seu peso")
leia(peso)

escreval("Insira sua altura")
leia(altura)

imc<-peso/(altura*altura)

escreval(imc)

Fimalgoritmo